import { Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { type FormEvent, type InputHTMLAttributes, type ReactNode, useState } from "react";
import { ApiFailure, request } from "./api/client";
import { useAuth } from "./auth/AuthProvider";
import { Button, Card, Input, Notice } from "./components/ui";
import { AccountAdministrationPage } from "./administration/AccountAdministrationPage";

const errorMessage = (error: unknown) => error instanceof ApiFailure ? `${error.message}${error.detail.correlationId ? ` Código de seguimiento: ${error.detail.correlationId}` : ""}` : "No se pudo completar la solicitud.";
const passwordPolicyMessage = "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un número.";
const validPassword = (password: string) => /(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}/.test(password);
function Layout({ children }: { children: ReactNode }) { return <main className="mx-auto min-h-screen max-w-6xl px-4 py-8 sm:px-6"><header className="mb-10 flex items-center justify-between"><a href="/" className="text-xl font-bold tracking-tight text-brand">CV Matcher</a><span className="text-sm text-slate-500">Reclutamiento con criterio humano</span></header>{children}</main>; }
function PublicPage({ title, children }: { title: string; children: ReactNode }) { return <Layout><div className="mx-auto max-w-md"><Card><h1 className="mb-2 text-2xl font-bold">{title}</h1>{children}</Card></div></Layout>; }
function Form({ children, onSubmit }: { children: ReactNode; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="mt-6 space-y-4" onSubmit={onSubmit}>{children}</form>; }
function Field({ label, ...props }: { label: string } & InputHTMLAttributes<HTMLInputElement>) { return <label className="block space-y-1"><span className="text-sm font-medium">{label}</span><Input {...props} /></label>; }
function PasswordPolicyHint() { return <p className="text-sm text-slate-600">{passwordPolicyMessage}</p>; }

function Login() { const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  return <PublicPage title="Bienvenido"><p className="text-slate-600">Ingresa para continuar con tu espacio de trabajo.</p><Form onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setPending(true); setError(""); try { await login(String(data.get("email")), String(data.get("password"))); navigate("/"); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }}><Field label="Correo" name="email" type="email" autoComplete="email" required /><Field label="Contraseña" name="password" type="password" autoComplete="current-password" required />{error && <Notice>{error}</Notice>}<Button className="w-full" disabled={pending}>{pending ? "Ingresando..." : "Iniciar sesión"}</Button></Form><div className="mt-5 flex justify-between text-sm"><a className="text-brand underline" href="/registro">Crear cuenta</a><a className="text-brand underline" href="/recuperar">Olvidé mi contraseña</a></div></PublicPage>; }
function TokenAction({ title, endpoint, password = false }: { title: string; endpoint: string; password?: boolean }) { const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); return <PublicPage title={title}><Form onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const replacement = String(data.get("password") ?? ""); if (password && !validPassword(replacement)) { setError(passwordPolicyMessage); return; } if (password && replacement !== data.get("passwordConfirmation")) { setError("Las contraseñas no coinciden."); return; } setPending(true); setError(""); try { await request<void>(endpoint, { method: "POST", body: JSON.stringify(password ? { token: data.get("token"), password: replacement } : { token: data.get("token") }) }); form.reset(); setNotice("La operación se completó correctamente."); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }}><Field label="Token recibido" name="token" required />{password && <><Field label="Nueva contraseña" name="password" type="password" autoComplete="new-password" required /><Field label="Confirma la nueva contraseña" name="passwordConfirmation" type="password" autoComplete="new-password" required /><PasswordPolicyHint /></>}{notice && <Notice tone="success">{notice}</Notice>}{error && <Notice>{error}</Notice>}<Button disabled={pending}>{pending ? "Procesando..." : "Confirmar"}</Button></Form></PublicPage>; }
function EmailAction({ title, endpoint, extraPassword = false }: { title: string; endpoint: string; extraPassword?: boolean }) { const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const { authenticatedRequest } = useAuth(); return <PublicPage title={title}><Form onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setPending(true); setError(""); try { const body = extraPassword ? { email: data.get("email"), currentPassword: data.get("password") } : { email: data.get("email") }; if (extraPassword) await authenticatedRequest<void>(endpoint, { method: "POST", body: JSON.stringify(body) }); else await request<void>(endpoint, { method: "POST", body: JSON.stringify(body) }); form.reset(); setNotice("Si corresponde, recibirás instrucciones por correo."); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }}><Field label="Correo" name="email" type="email" required />{extraPassword && <Field label="Contraseña actual" name="password" type="password" autoComplete="current-password" required />}{notice && <Notice tone="success">{notice}</Notice>}{error && <Notice>{error}</Notice>}<Button disabled={pending}>{pending ? "Enviando..." : "Continuar"}</Button></Form></PublicPage>; }
function Register() { const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); return <PublicPage title="Crea tu cuenta"><Form onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const password = String(data.get("password") ?? ""); if (!validPassword(password)) { setError(passwordPolicyMessage); return; } if (password !== data.get("passwordConfirmation")) { setError("Las contraseñas no coinciden."); return; } setPending(true); setError(""); try { await request<void>("/auth/register", { method: "POST", body: JSON.stringify({ fullName: data.get("name"), email: data.get("email"), password }) }); form.reset(); setNotice("Revisa tu correo para continuar con la verificación."); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }}><Field label="Nombre completo" name="name" autoComplete="name" required /><Field label="Correo" name="email" type="email" autoComplete="email" required /><Field label="Contraseña" name="password" type="password" autoComplete="new-password" required /><Field label="Confirma tu contraseña" name="passwordConfirmation" type="password" autoComplete="new-password" required /><PasswordPolicyHint />{notice && <Notice tone="success">{notice}</Notice>}{error && <Notice>{error}</Notice>}<Button disabled={pending}>{pending ? "Creando cuenta..." : "Crear cuenta"}</Button></Form></PublicPage>; }
function RequireAuth({ children, allowPasswordChange = false }: { children: ReactNode; allowPasswordChange?: boolean }) {
  const { user, loading } = useAuth();
  const location = useLocation();
  if (loading) return <Layout><p aria-live="polite">Comprobando sesión...</p></Layout>;
  if (!user) return <Navigate to="/ingresar" replace state={{ from: location }} />;
  if (user.forcePasswordChange && !allowPasswordChange) return <Navigate to="/cambiar-contrasena" replace />;
  return children;
}
function Protected() { return <RequireAuth><Dashboard /></RequireAuth>; }
function RequireAdmin({ children }: { children: ReactNode }) { const { user, loading } = useAuth(); if (loading) return <Layout><p aria-live="polite">Comprobando sesión...</p></Layout>; if (!user) return <Navigate to="/ingresar" replace />; if (user.forcePasswordChange || user.role !== "ADMIN") return <Navigate to="/" replace />; return children; }
function Dashboard() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  if (!user) return <Navigate to="/ingresar" replace />;
  return <Layout><Card><p className="text-sm font-semibold text-brand">SESIÓN ACTIVA</p><h1 className="mt-2 text-3xl font-bold">Hola, {user.fullName}</h1><p className="mt-2 text-slate-600">Tu cuenta está lista para los módulos disponibles.</p>{user.role === "ADMIN" && <p className="mt-4"><a className="font-semibold text-brand underline" href="/administracion/usuarios">Administrar cuentas</a></p>}<Button className="mt-6" variant="secondary" onClick={() => { void logout().finally(() => navigate("/ingresar")); }}>Cerrar sesión</Button></Card></Layout>;
}
function PasswordChange() { const { authenticatedRequest, clearSession } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); return <PublicPage title="Cambia tu contraseña"><Form onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const replacement = String(data.get("next") ?? ""); if (!validPassword(replacement)) { setError(passwordPolicyMessage); return; } if (replacement !== data.get("confirmation")) { setError("Las contraseñas no coinciden."); return; } setPending(true); setError(""); try { await authenticatedRequest<void>("/auth/password/change", { method: "POST", body: JSON.stringify({ currentPassword: data.get("current"), newPassword: replacement }) }); clearSession(); navigate("/ingresar"); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }}><Field label="Contraseña actual" name="current" type="password" autoComplete="current-password" required /><Field label="Nueva contraseña" name="next" type="password" autoComplete="new-password" required /><Field label="Confirma la nueva contraseña" name="confirmation" type="password" autoComplete="new-password" required /><PasswordPolicyHint />{error && <Notice>{error}</Notice>}<Button disabled={pending}>{pending ? "Actualizando contraseña..." : "Actualizar contraseña"}</Button></Form></PublicPage>; }
export function App() { return <Routes><Route path="/" element={<Protected />} /><Route path="/administracion/usuarios" element={<RequireAdmin><AccountAdministrationPage /></RequireAdmin>} /><Route path="/ingresar" element={<Login />} /><Route path="/registro" element={<Register />} /><Route path="/verificar-correo" element={<TokenAction title="Verifica tu correo" endpoint="/auth/email-verification/confirm" />} /><Route path="/reenviar-verificacion" element={<EmailAction title="Reenviar verificación" endpoint="/auth/email-verification/resend" />} /><Route path="/recuperar" element={<EmailAction title="Recupera tu acceso" endpoint="/auth/password-reset/request" />} /><Route path="/restablecer-contrasena" element={<TokenAction title="Restablece tu contraseña" endpoint="/auth/password-reset/confirm" password />} /><Route path="/cambiar-contrasena" element={<RequireAuth allowPasswordChange><PasswordChange /></RequireAuth>} /><Route path="/cambiar-correo" element={<RequireAuth><EmailAction title="Cambia tu correo" endpoint="/auth/email-change/request" extraPassword /></RequireAuth>} /><Route path="/confirmar-correo" element={<TokenAction title="Confirma tu nuevo correo" endpoint="/auth/email-change/confirm" />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
