/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/vacancies/{vacancyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar una vacante */
        get: operations["get"];
        /**
         * Editar vacante activa
         * @description Reemplaza de forma atómica los requisitos si expectedVersion coincide.
         */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar vacantes
         * @description Devuelve vacantes compartidas paginadas; por defecto sólo las activas.
         */
        get: operations["list"];
        put?: never;
        /**
         * Crear vacante
         * @description Crea una vacante activa con un rango de recepción en America/La_Paz.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/{vacancyId}/report-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar trabajos de una vacante
         * @description Página compartida ordenada por createdAt descendente e id ascendente. Los estados son QUEUED, DISCOVERING, INGESTING_DOCUMENTS, ANALYZING, COMPLETED, COMPLETED_WITH_WARNINGS, FAILED, REAUTHORIZATION_REQUIRED y CANCELLED.
         */
        get: operations["list_1"];
        put?: never;
        /**
         * Encolar reporte
         * @description Persiste un trabajo durable en estado QUEUED; no ejecuta procesamiento durante la solicitud HTTP.
         */
        post: operations["enqueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/{vacancyId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reactivar vacante
         * @description Reactiva una vacante archivada cuando expectedVersion coincide. Repetir la transición ya satisfecha no produce cambios.
         */
        post: operations["reactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacancies/{vacancyId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archivar vacante
         * @description Archiva una vacante activa cuando expectedVersion coincide. Repetir la transición ya satisfecha no produce cambios.
         */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report-jobs/{jobId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reintentar trabajo terminal reintentable */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report-jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancelar trabajo activo */
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar reclutador
         * @description Crea una cuenta pendiente de verificación. La respuesta es neutral para no enumerar cuentas.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar access token
         * @description Requiere la cookie cv_refresh y el valor de XSRF-TOKEN en el header X-CSRF-TOKEN. Rota el refresh token.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambiar contraseña */
        post: operations["passwordChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar restablecimiento de contraseña
         * @description La respuesta es neutral aunque la cuenta no exista o no esté activa.
         */
        post: operations["resetRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar restablecimiento de contraseña */
        post: operations["resetConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión
         * @description Requiere la cookie cv_refresh y el header X-CSRF-TOKEN. Expira ambas cookies.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Devuelve access token, expiración e identidad segura; establece cookies cv_refresh y XSRF-TOKEN.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email-verification/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenviar verificación
         * @description Máximo tres reenvíos por cuenta y hora. La respuesta es neutral.
         */
        post: operations["resend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email-verification/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar correo */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email-change/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar cambio de correo
         * @description Requiere bearer JWT y contraseña actual.
         */
        post: operations["emailChangeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email-change/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar cambio de correo */
        post: operations["emailChangeConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activar o desactivar cuenta */
        patch: operations["changeStatus"];
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar rol de cuenta */
        patch: operations["changeRole"];
        trace?: never;
    };
    "/api/v1/report-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar un trabajo
         * @description Devuelve el snapshot de la vacante y requisitos; nunca expone lease, solicitante, sesiones, tokens ni documentos.
         */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar identidad actual */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar cuentas
         * @description Requiere un ADMIN con sesión vigente.
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequirementRequest: {
            description: string;
            /** Format: int32 */
            weight: number;
            mandatory: boolean;
        };
        VacancyWriteRequest: {
            title: string;
            description: string;
            /** Format: date */
            dateFrom: string;
            /** Format: date */
            dateTo: string;
            /** Format: int64 */
            expectedVersion: number;
            requirements: components["schemas"]["RequirementRequest"][];
        };
        /** @description Error seguro devuelto por la API */
        ApiError: {
            /**
             * Format: int32
             * @example 400
             */
            status?: number;
            /** @example VALIDATION_ERROR */
            code?: string;
            /** @example La solicitud no es válida. */
            message?: string;
            /**
             * Format: date-time
             * @example 2026-09-03T17:40:41Z
             */
            timestamp?: string;
            /** @example /api/v1/auth/register */
            path?: string;
            /**
             * Format: uuid
             * @example 5fe5c7e2-2f92-4bf3-927d-92077e3acd5
             */
            correlationId?: string;
        };
        Requirement: {
            /** Format: uuid */
            id?: string;
            description?: string;
            /** Format: int32 */
            weight?: number;
            mandatory?: boolean;
            /** Format: int32 */
            position?: number;
        };
        VacancyDetail: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** Format: date */
            dateFrom?: string;
            /** Format: date */
            dateTo?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED";
            /** Format: int64 */
            version?: number;
            requirements?: components["schemas"]["Requirement"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EmptyRequest: unknown;
        JobAccepted: {
            /** Format: uuid */
            jobId?: string;
            /** @enum {string} */
            status?: "QUEUED" | "DISCOVERING" | "INGESTING_DOCUMENTS" | "ANALYZING" | "COMPLETED" | "COMPLETED_WITH_WARNINGS" | "FAILED" | "REAUTHORIZATION_REQUIRED" | "CANCELLED";
            /** Format: int32 */
            attempt?: number;
            statusUrl?: string;
        };
        VersionRequest: {
            /** Format: int64 */
            expectedVersion: number;
        };
        RegisterRequest: {
            /** @example Ana Reclutadora */
            fullName: string;
            /**
             * Format: email
             * @example ana@example.test
             */
            email: string;
            /** @example ClaveSegura1 */
            password: string;
        };
        TokenResponse: {
            /** @example eyJhbGciOiJIUzI1NiJ9... */
            accessToken?: string;
            /** @example Bearer */
            tokenType?: string;
            /**
             * Format: int64
             * @example 900
             */
            expiresIn?: number;
            user?: components["schemas"]["UserInfo"];
            /** @example false */
            forcePasswordChange?: boolean;
        };
        UserInfo: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
            role?: string;
            status?: string;
            forcePasswordChange?: boolean;
        };
        PasswordChangeRequest: {
            /** @example ClaveActual1 */
            currentPassword: string;
            /** @example ClaveNueva2 */
            newPassword: string;
        };
        EmailRequest: {
            /**
             * Format: email
             * @example ana@example.test
             */
            email: string;
        };
        PasswordTokenRequest: {
            /** @example token-recibido-por-correo */
            token: string;
            /** @example ClaveSegura1 */
            password: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example ana@example.test
             */
            email: string;
            /** @example ClaveSegura1 */
            password: string;
        };
        TokenRequest: {
            /** @example token-recibido-por-correo */
            token: string;
        };
        EmailChangeRequest: {
            /**
             * Format: email
             * @example nuevo@example.test
             */
            email: string;
            /** @example ClaveActual1 */
            currentPassword: string;
        };
        StatusRequest: {
            /**
             * @example DISABLED
             * @enum {string}
             */
            status: "PENDING_VERIFICATION" | "ACTIVE" | "DISABLED";
        };
        RoleRequest: {
            /**
             * @example ADMIN
             * @enum {string}
             */
            role: "RECRUITER" | "ADMIN";
        };
        VacancyPage: {
            items?: components["schemas"]["VacancySummary"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        VacancySummary: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED";
            /** Format: int64 */
            version?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        JobPage: {
            items?: components["schemas"]["JobSummary"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        JobSummary: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            vacancyId?: string;
            /** Format: int64 */
            vacancyVersion?: number;
            vacancyTitle?: string;
            /** @enum {string} */
            status?: "QUEUED" | "DISCOVERING" | "INGESTING_DOCUMENTS" | "ANALYZING" | "COMPLETED" | "COMPLETED_WITH_WARNINGS" | "FAILED" | "REAUTHORIZATION_REQUIRED" | "CANCELLED";
            /** Format: int32 */
            attempt?: number;
            failureCode?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        JobDetail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            vacancyId?: string;
            /** Format: int64 */
            vacancyVersion?: number;
            vacancyTitle?: string;
            /** Format: date-time */
            receivedFromUtc?: string;
            /** Format: date-time */
            receivedToUtcExclusive?: string;
            /** @enum {string} */
            status?: "QUEUED" | "DISCOVERING" | "INGESTING_DOCUMENTS" | "ANALYZING" | "COMPLETED" | "COMPLETED_WITH_WARNINGS" | "FAILED" | "REAUTHORIZATION_REQUIRED" | "CANCELLED";
            /** Format: int32 */
            attempt?: number;
            failureCode?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            requirements?: components["schemas"]["RequirementSnapshot"][];
        };
        RequirementSnapshot: {
            description?: string;
            /** Format: int32 */
            weight?: number;
            mandatory?: boolean;
            /** Format: int32 */
            position?: number;
        };
        AccountPage: {
            items?: components["schemas"]["AccountSummary"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        AccountSummary: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
            /** @enum {string} */
            role?: "RECRUITER" | "ADMIN";
            /** @enum {string} */
            status?: "PENDING_VERIFICATION" | "ACTIVE" | "DISABLED";
            /** Format: date-time */
            emailVerifiedAt?: string;
            forcePasswordChange?: boolean;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de vacante */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VacancyDetail"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyWriteRequest"];
            };
        };
        responses: {
            /** @description Vacante actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VacancyDetail"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante archivada o versión desactualizada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Solicitud inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "ARCHIVED";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de vacantes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VacancyPage"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Filtros o paginación inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyWriteRequest"];
            };
        };
        responses: {
            /** @description Vacante creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VacancyDetail"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Solicitud inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                /** @description Filtro exacto de estado */
                status?: "QUEUED" | "DISCOVERING" | "INGESTING_DOCUMENTS" | "ANALYZING" | "COMPLETED" | "COMPLETED_WITH_WARNINGS" | "FAILED" | "REAUTHORIZATION_REQUIRED" | "CANCELLED";
                /** @description Página desde 0 */
                page?: number;
                /** @description Elementos por página, de 1 a 100 */
                size?: number;
            };
            header?: never;
            path: {
                vacancyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de trabajos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobPage"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Filtro, UUID o paginación inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    enqueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Trabajo encolado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "code": "VACANCY_NOT_FOUND",
                     *       "message": "La operación no puede completarse."
                     *     }
                     */
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante archivada o trabajo activo existente */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 409,
                     *       "code": "ACTIVE_JOB_EXISTS",
                     *       "message": "La operación no puede completarse."
                     *     }
                     */
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Body distinto de {} o identificador inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description Vacante reactivada o ya activa */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Versión desactualizada o transición no permitida */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Solicitud inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionRequest"];
            };
        };
        responses: {
            /** @description Vacante archivada o ya archivada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Vacante inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Versión desactualizada o transición no permitida */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Solicitud inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Nuevo trabajo QUEUED desde snapshot previo */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Trabajo inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Trabajo no reintentable o existe un trabajo activo */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Body distinto de {} o UUID inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Trabajo cancelado o ya cancelado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Trabajo inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Trabajo terminal no cancelable */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Body distinto de {} o UUID inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Solicitud aceptada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Política de contraseña incumplida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos de registro inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header: {
                /** @description Valor de la cookie XSRF-TOKEN */
                "X-CSRF-TOKEN": string;
            };
            path?: never;
            cookie: {
                /** @description Cookie HttpOnly de sesión */
                cv_refresh: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Token renovado */
            200: {
                headers: {
                    /** @description Cookies refresh y CSRF rotadas */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description CSRF inválido o ausente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    passwordChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Contraseña actualizada y sesiones revocadas */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Contraseña nueva inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Bearer JWT inválido o contraseña actual incorrecta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos ausentes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    resetRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Solicitud aceptada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Correo inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    resetConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordTokenRequest"];
            };
        };
        responses: {
            /** @description Contraseña actualizada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token o política de contraseña inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos ausentes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Valor de la cookie XSRF-TOKEN */
                "X-CSRF-TOKEN": string;
            };
            path?: never;
            cookie: {
                /** @description Cookie HttpOnly de sesión */
                cv_refresh: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Sesión cerrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF inválido o ausente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sesión creada */
            200: {
                headers: {
                    /** @description Cookies cv_refresh y XSRF-TOKEN */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Credenciales inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos de login inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    resend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Solicitud aceptada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Correo inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Cuenta verificada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token inválido, vencido o usado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Token ausente */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    emailChangeRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChangeRequest"];
            };
        };
        responses: {
            /** @description Solicitud aceptada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bearer JWT o contraseña actual inválidos */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Debe cambiar contraseña */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Correo ya utilizado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Datos inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    emailChangeConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Correo actualizado y sesiones revocadas */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token inválido, vencido o usado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Correo ya utilizado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Token ausente */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusRequest"];
            };
        };
        responses: {
            /** @description Estado aplicado o ya persistido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Cuenta inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflicto de administración */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Solicitud inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description Rol aplicado o ya persistido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Cuenta inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflicto de administración */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Solicitud inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de trabajo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobDetail"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Trabajo inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description UUID inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identidad segura */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserInfo"];
                };
            };
            /** @description Bearer JWT inválido o ausente */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                role?: "RECRUITER" | "ADMIN";
                status?: "PENDING_VERIFICATION" | "ACTIVE" | "DISABLED";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de cuentas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountPage"];
                };
            };
            /** @description Bearer inválido o sesión revocada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Rol insuficiente */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Filtros o paginación inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
