spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    root: INFO
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
