spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5430/cv-matcher}
    username: ${DATABASE_USERNAME:salaco}
    password: ${DATABASE_PASSWORD:}

logging:
  level:
    root: INFO
